stages:
  - test
  - deploy

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

sast:
  variables:
    SAST_EXCLUDED_PATHS: test/**

# Lint js files.
lint-js:
 image: node
 stage: test
 tags:
   - docker
 script:
   - npm install -g eslint
   - eslint --ignore-pattern "**/*.min.js" $CI_PROJECT_DIR

# Performs unit testing.
unit-test:
  services:
    - prysmo/hello-prysmo:v0.0.2
  variables:
    HELLO_PRYSMO: ws://prysmo-hello-prysmo:7667
  coverage: '/Statements\s*:\s*(\d+(?:\.\d+)?\%)/'
  image: cypress/base
  stage: test
  artifacts:
    paths: [coverage]
  tags:
    - docker
  script:
    - npm i -g nyc
    - npm i
    - npm run instrument
    - npm t
    - npm run coverage

# Publish package to NPM.
publish:
  stage: deploy
  image: node
  tags:
    - docker
  only:
    - tags
    - triggers
  except:
    variables:
      - $CI_COMMIT_TAG =~ /beta/
  script:
    - mkdir dist
    - npm i -g uglify-es
    - npm run minify
    - npm install -g npm-cli-login
    - npm-cli-login
    - npm publish
